// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccpnlqdlgapejgfcglez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcG5scWRsZ2FwZWpnZmNnbGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzQ1NzksImV4cCI6MjA2MDgxMDU3OX0.14ongbXJAVcCIo_GAOwoeHnARnbX1Tq-yUAG-PRN0x8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);