// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukrinlfguerdzmyuboyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcmlubGZndWVyZHpteXVib3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjE3NTUsImV4cCI6MjA2NDIzNzc1NX0.U8iJSyltrikqVW2d5nH0IOKqy7hC1ekyGw3NMVl2LyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);